/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_INCLUDED__
#define __PLUGINEDITOR_H_INCLUDED__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/** This is the editor component that our filter will display.
*/
class NewProjectAudioProcessorEditor  : public AudioProcessorEditor,
                                            public SliderListener,
                                            public Timer
{
public:
    NewProjectAudioProcessorEditor (NewProjectAudioProcessor* ownerFilter);
    ~NewProjectAudioProcessorEditor();

    //==============================================================================
    void timerCallback() override;
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged (Slider*) override;

private:
    Label innerLevelLabel, outerLevelLabel, removeNumLabel, keepNumLabel,
		  removeAmountLabel, noiseCutoffLabel, noiseAmountLabel;
    Slider innerLevelSlider, outerLevelSlider, removeNumSlider, keepNumSlider,
		  removeAmountSlider, noiseCutoffSlider, noiseAmountSlider;
	ScopedPointer<ResizableCornerComponent> resizer;
    ComponentBoundsConstrainer resizeLimits;

    AudioPlayHead::CurrentPositionInfo lastDisplayedPosition;

    NewProjectAudioProcessor* getProcessor() const
    {
        return static_cast <NewProjectAudioProcessor*> (getAudioProcessor());
    }

    void displayPositionInfo (const AudioPlayHead::CurrentPositionInfo& pos);
};


#endif  // __PLUGINEDITOR_H_4ACCBAA__
